# Generated by Django 3.1.5 on 2021-02-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(blank=True, choices=[('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Mr', 'Mr')], default='', max_length=60),
        ),
    ]
