# Generated by Django 3.1.5 on 2021-02-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210131_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prefix',
            field=models.CharField(choices=[('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Mr', 'Mr')], default='', max_length=10),
        ),
    ]
